# first we print the list of students
puts "The students of my cohort at Makers Academy"
puts "------------"
puts "John Kiely"
puts "Chris Batts"
puts "Ben Hutchinson"
puts "Ayo Obembe"
puts "Mishal"
puts "Chris Handley"
puts "Giorgia Amici"
puts "Attila"
puts "Pavel Redics"
puts "Janacuq"
puts "Edward Byne"
puts "Arfah"
puts "langesi"
puts "Richard Lake"
puts "CZC8190BMC"
puts "Nick Dyer"
puts "Izzy Markwick"
puts "Alan Bridger"
puts "Alex Blease"
puts "Shan Hasan"
puts "Claudia Callisto"
puts "Dale Stevens"
puts "Abdul Hassan"
puts "Alan Bridger"
puts "Alexander Levin"
puts "Ana Nogal"
puts "Andrew Harrison"
puts "Andrew Hercules"
puts "Andrew Snead"
puts "Anna Jerofejeva"
puts "Bernard Mordan"
puts "Camilla van Klinken"
puts "Clare Trembath"
puts "Colin Smif"
puts "Contra Mundi"
puts "Craig Horsborough"
puts "Daniel Cutler"
puts "Daniel Le Dosquet"
puts "Elena Garrone"
puts "Ella Schofield"
puts "Fad Fad"
puts "Jana Sanchez"
puts "James Carter"
puts "Johnny Lakin"
puts "Karin Nielsen"
puts "Marcherita Serino"
puts "Ming Chan"
puts "Nicole Pellicena"
puts "Nikesh Ashar"
puts "Sandrine Zhang-Ferron"
puts "Shan Hasan"
puts "Simon Lange"
puts "Stephen Giles"
puts "Tim Scully"
puts "Victoria Stepanovna"
puts "Yvette Cook"
puts "Zeeshan Rasool"
#finally, we print the total
print "Overall, we have "
#it's important that print() doesn't add new line characters
print 57
print " great students"